version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql
